// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subrequests.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createSubRequest = `-- name: CreateSubRequest :execresult
INSERT INTO sub_requests (show_id, posted_by_user_id, taken_by_user_id, start_time, end_time, notes, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSubRequestParams struct {
	ShowID         int64          `json:"show_id"`
	PostedByUserID int64          `json:"posted_by_user_id"`
	TakenByUserID  sql.NullInt64  `json:"taken_by_user_id"`
	StartTime      time.Time      `json:"start_time"`
	EndTime        time.Time      `json:"end_time"`
	Notes          sql.NullString `json:"notes"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateSubRequest(ctx context.Context, arg CreateSubRequestParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSubRequest,
		arg.ShowID,
		arg.PostedByUserID,
		arg.TakenByUserID,
		arg.StartTime,
		arg.EndTime,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const deleteSubRequest = `-- name: DeleteSubRequest :execresult
DELETE FROM sub_requests WHERE id = ?
`

func (q *Queries) DeleteSubRequest(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteSubRequest, id)
}

const getSubRequestByID = `-- name: GetSubRequestByID :one
SELECT id, show_id, posted_by_user_id, taken_by_user_id, start_time, end_time, notes, created_at, updated_at
FROM sub_requests
WHERE id = ?
`

func (q *Queries) GetSubRequestByID(ctx context.Context, id int64) (SubRequest, error) {
	row := q.db.QueryRowContext(ctx, getSubRequestByID, id)
	var i SubRequest
	err := row.Scan(
		&i.ID,
		&i.ShowID,
		&i.PostedByUserID,
		&i.TakenByUserID,
		&i.StartTime,
		&i.EndTime,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubRequests = `-- name: ListSubRequests :many
SELECT sr.id, sr.show_id, sr.posted_by_user_id, sr.taken_by_user_id, u.email, COALESCE(u2.email, '') AS taker_email, sr.start_time, sr.end_time, sr.notes, sr.created_at, sr.updated_at
FROM sub_requests sr
JOIN users u ON sr.posted_by_user_id = u.id
LEFT JOIN users u2 ON sr.taken_by_user_id = u2.id
ORDER BY sr.start_time ASC
`

type ListSubRequestsRow struct {
	ID             int64          `json:"id"`
	ShowID         int64          `json:"show_id"`
	PostedByUserID int64          `json:"posted_by_user_id"`
	TakenByUserID  sql.NullInt64  `json:"taken_by_user_id"`
	Email          string         `json:"email"`
	TakerEmail     string         `json:"taker_email"`
	StartTime      time.Time      `json:"start_time"`
	EndTime        time.Time      `json:"end_time"`
	Notes          sql.NullString `json:"notes"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

func (q *Queries) ListSubRequests(ctx context.Context) ([]ListSubRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSubRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubRequestsRow
	for rows.Next() {
		var i ListSubRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShowID,
			&i.PostedByUserID,
			&i.TakenByUserID,
			&i.Email,
			&i.TakerEmail,
			&i.StartTime,
			&i.EndTime,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const takeSubRequest = `-- name: TakeSubRequest :execresult
UPDATE sub_requests SET taken_by_user_id = ?, updated_at = ? WHERE id = ? AND taken_by_user_id IS NULL
`

type TakeSubRequestParams struct {
	TakenByUserID sql.NullInt64 `json:"taken_by_user_id"`
	UpdatedAt     sql.NullTime  `json:"updated_at"`
	ID            int64         `json:"id"`
}

func (q *Queries) TakeSubRequest(ctx context.Context, arg TakeSubRequestParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, takeSubRequest, arg.TakenByUserID, arg.UpdatedAt, arg.ID)
}

const untakeSubRequest = `-- name: UntakeSubRequest :execresult
UPDATE sub_requests SET taken_by_user_id = NULL, updated_at = ? WHERE id = ?
`

type UntakeSubRequestParams struct {
	UpdatedAt sql.NullTime `json:"updated_at"`
	ID        int64        `json:"id"`
}

func (q *Queries) UntakeSubRequest(ctx context.Context, arg UntakeSubRequestParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, untakeSubRequest, arg.UpdatedAt, arg.ID)
}
