// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for PatchSubRequestsIdJSONBodyAction.
const (
	Take   PatchSubRequestsIdJSONBodyAction = "take"
	Untake PatchSubRequestsIdJSONBodyAction = "untake"
)

// Valid indicates whether the value is a known member of the PatchSubRequestsIdJSONBodyAction enum.
func (e PatchSubRequestsIdJSONBodyAction) Valid() bool {
	switch e {
	case Take:
		return true
	case Untake:
		return true
	default:
		return false
	}
}

// Defines values for PostUsersFormdataBodyRole.
const (
	PostUsersFormdataBodyRoleAdmin  PostUsersFormdataBodyRole = "admin"
	PostUsersFormdataBodyRoleMember PostUsersFormdataBodyRole = "member"
)

// Valid indicates whether the value is a known member of the PostUsersFormdataBodyRole enum.
func (e PostUsersFormdataBodyRole) Valid() bool {
	switch e {
	case PostUsersFormdataBodyRoleAdmin:
		return true
	case PostUsersFormdataBodyRoleMember:
		return true
	default:
		return false
	}
}

// Defines values for PatchUsersIdJSONBodyRole.
const (
	PatchUsersIdJSONBodyRoleAdmin  PatchUsersIdJSONBodyRole = "admin"
	PatchUsersIdJSONBodyRoleMember PatchUsersIdJSONBodyRole = "member"
)

// Valid indicates whether the value is a known member of the PatchUsersIdJSONBodyRole enum.
func (e PatchUsersIdJSONBodyRole) Valid() bool {
	switch e {
	case PatchUsersIdJSONBodyRoleAdmin:
		return true
	case PatchUsersIdJSONBodyRoleMember:
		return true
	default:
		return false
	}
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email openapi_types.Email `json:"email"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message *string `json:"message,omitempty"`
}

// GetAuthVerifyParams defines parameters for GetAuthVerify.
type GetAuthVerifyParams struct {
	Token string `form:"token" json:"token"`
}

// PostSubRequestsFormdataBody defines parameters for PostSubRequests.
type PostSubRequestsFormdataBody struct {
	EndTime   string  `form:"end_time" json:"end_time"`
	Notes     *string `form:"notes,omitempty" json:"notes,omitempty"`
	Show      int     `form:"show" json:"show"`
	StartTime string  `form:"start_time" json:"start_time"`
}

// PatchSubRequestsIdJSONBody defines parameters for PatchSubRequestsId.
type PatchSubRequestsIdJSONBody struct {
	Action PatchSubRequestsIdJSONBodyAction `json:"action"`
}

// PatchSubRequestsIdJSONBodyAction defines parameters for PatchSubRequestsId.
type PatchSubRequestsIdJSONBodyAction string

// PostUsersFormdataBody defines parameters for PostUsers.
type PostUsersFormdataBody struct {
	Email openapi_types.Email        `form:"email" json:"email"`
	Role  *PostUsersFormdataBodyRole `form:"role,omitempty" json:"role,omitempty"`
}

// PostUsersFormdataBodyRole defines parameters for PostUsers.
type PostUsersFormdataBodyRole string

// PatchUsersIdJSONBody defines parameters for PatchUsersId.
type PatchUsersIdJSONBody struct {
	IsEnabled *bool                     `json:"is_enabled,omitempty"`
	Role      *PatchUsersIdJSONBodyRole `json:"role,omitempty"`
}

// PatchUsersIdJSONBodyRole defines parameters for PatchUsersId.
type PatchUsersIdJSONBodyRole string

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// PostAuthLoginFormdataRequestBody defines body for PostAuthLogin for application/x-www-form-urlencoded ContentType.
type PostAuthLoginFormdataRequestBody = LoginRequest

// PostSubRequestsFormdataRequestBody defines body for PostSubRequests for application/x-www-form-urlencoded ContentType.
type PostSubRequestsFormdataRequestBody PostSubRequestsFormdataBody

// PatchSubRequestsIdJSONRequestBody defines body for PatchSubRequestsId for application/json ContentType.
type PatchSubRequestsIdJSONRequestBody PatchSubRequestsIdJSONBody

// PostUsersFormdataRequestBody defines body for PostUsers for application/x-www-form-urlencoded ContentType.
type PostUsersFormdataRequestBody PostUsersFormdataBody

// PatchUsersIdJSONRequestBody defines body for PatchUsersId for application/json ContentType.
type PatchUsersIdJSONRequestBody PatchUsersIdJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Home page or login page
	// (GET /)
	Get(w http.ResponseWriter, r *http.Request)
	// Admin dashboard
	// (GET /admin)
	GetAdmin(w http.ResponseWriter, r *http.Request)
	// Authenticated application page
	// (GET /app)
	GetApp(w http.ResponseWriter, r *http.Request)
	// Request a magic link for login
	// (POST /auth/login)
	PostAuthLogin(w http.ResponseWriter, r *http.Request)
	// Logout and invalidate sessions
	// (POST /auth/logout)
	PostAuthLogout(w http.ResponseWriter, r *http.Request)
	// Verify magic link and create session
	// (GET /auth/verify)
	GetAuthVerify(w http.ResponseWriter, r *http.Request, params GetAuthVerifyParams)
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Create a new sub request
	// (POST /sub-requests)
	PostSubRequests(w http.ResponseWriter, r *http.Request)
	// Delete a sub request
	// (DELETE /sub-requests/{id})
	DeleteSubRequestsId(w http.ResponseWriter, r *http.Request, id int)
	// Take or untake a sub request
	// (PATCH /sub-requests/{id})
	PatchSubRequestsId(w http.ResponseWriter, r *http.Request, id int)
	// Create a new user
	// (POST /users)
	PostUsers(w http.ResponseWriter, r *http.Request)
	// Import users from Spinitron
	// (POST /users/import/spinitron)
	PostUsersImportSpinitron(w http.ResponseWriter, r *http.Request)
	// Update a user's status
	// (PATCH /users/{id})
	PatchUsersId(w http.ResponseWriter, r *http.Request, id int)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Home page or login page
// (GET /)
func (_ Unimplemented) Get(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Admin dashboard
// (GET /admin)
func (_ Unimplemented) GetAdmin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Authenticated application page
// (GET /app)
func (_ Unimplemented) GetApp(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Request a magic link for login
// (POST /auth/login)
func (_ Unimplemented) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout and invalidate sessions
// (POST /auth/logout)
func (_ Unimplemented) PostAuthLogout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Verify magic link and create session
// (GET /auth/verify)
func (_ Unimplemented) GetAuthVerify(w http.ResponseWriter, r *http.Request, params GetAuthVerifyParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new sub request
// (POST /sub-requests)
func (_ Unimplemented) PostSubRequests(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a sub request
// (DELETE /sub-requests/{id})
func (_ Unimplemented) DeleteSubRequestsId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Take or untake a sub request
// (PATCH /sub-requests/{id})
func (_ Unimplemented) PatchSubRequestsId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new user
// (POST /users)
func (_ Unimplemented) PostUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Import users from Spinitron
// (POST /users/import/spinitron)
func (_ Unimplemented) PostUsersImportSpinitron(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a user's status
// (PATCH /users/{id})
func (_ Unimplemented) PatchUsersId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Get operation middleware
func (siw *ServerInterfaceWrapper) Get(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Get(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdmin operation middleware
func (siw *ServerInterfaceWrapper) GetAdmin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdmin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApp operation middleware
func (siw *ServerInterfaceWrapper) GetApp(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthVerify operation middleware
func (siw *ServerInterfaceWrapper) GetAuthVerify(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAuthVerifyParams

	// ------------- Required query parameter "token" -------------

	if paramValue := r.URL.Query().Get("token"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "token"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "token", r.URL.Query(), &params.Token, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthVerify(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostSubRequests operation middleware
func (siw *ServerInterfaceWrapper) PostSubRequests(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostSubRequests(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSubRequestsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteSubRequestsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSubRequestsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchSubRequestsId operation middleware
func (siw *ServerInterfaceWrapper) PatchSubRequestsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchSubRequestsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUsers operation middleware
func (siw *ServerInterfaceWrapper) PostUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUsersImportSpinitron operation middleware
func (siw *ServerInterfaceWrapper) PostUsersImportSpinitron(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsersImportSpinitron(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchUsersId operation middleware
func (siw *ServerInterfaceWrapper) PatchUsersId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchUsersId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/", wrapper.Get)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin", wrapper.GetAdmin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/app", wrapper.GetApp)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.PostAuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.PostAuthLogout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/verify", wrapper.GetAuthVerify)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/sub-requests", wrapper.PostSubRequests)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/sub-requests/{id}", wrapper.DeleteSubRequestsId)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/sub-requests/{id}", wrapper.PatchSubRequestsId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users", wrapper.PostUsers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/import/spinitron", wrapper.PostUsersImportSpinitron)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/users/{id}", wrapper.PatchUsersId)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xX224bNxD9FYIt0ARYexU7fajeXBdthMSNYcd9CYyAWo60jJYXk7O+1NC/F0NK1l5k",
	"WRUcwy/2ajlLzjlz5pC854XVzhowGPjwnoeiBC3i4yc7VeYMrmoISL+dtw48KoijoIWq6GFivRbIh4s3",
	"Gcc7B3zIA3plpnw+z7iHq1p5kHz4dRF1+RBmx9+hQD7P+AmEIKZwBsFZE6C/pE4B9NhfozMdvVJmYilY",
	"Qii8cqis4UN+dDpiE+vZkfLs2F6DZwFCUNYwLYyYggaDTBjJQmlvGHpRzJSZ7hMwhRWtsfry6HTEM34N",
	"PqS53+0P9geExTowwik+5If7g/1DnnEnsIwocvozhUgpoROU10jyIf8LkBNZCX8MPhgM6F9hDYKJnyDc",
	"Yl6irlbVWkfIPOvA/vDl5BNbzkPDodZa+DsashqYE1Ng1rOKqh5/xahcSK3MppSPYsAL5Z3x94N3/Zpe",
	"GFFjab36F2QKOuwH/Wn9WEkJpgM/AmBShHJshZcL2M5tBO3cq4LcBlRjCQZVIRAkE85V9EgKb5S1xjKP",
	"tY59ZsManKc2IM0VjYCnNoaAv1t510HaWCP/HqxpA/7Zw4QP+U/5ymryhc/kLZOhzJpT3e7d3NzskcHs",
	"1b4CU1hJJrLj3C0jQl/D/MkK7o6ra2ZrynwipqpglTIzFh4qPehXemSuRaUk8w2WVsVe4GOC6dV8k2Uj",
	"t4tta9yq2hTX4eZwcNDP7Ayk8lAgQ8tKq2EXsablouGqBFQgLC05NPK/Bq8mdxubssbynxRFfuuFBgQf",
	"+PDrPSed86saPI0ZoakD0c5gqeuVKrINrXq5CyvkqmQnj5GzrK/1DG4dJcJSZm2iErJmlYmzwkODr0RX",
	"CaLCchNTH1LEdg7mKqE6yodboV3cCz9/XLPj96T++WN3y4kJsKKEYpaSDvV4b6HwsFmk5/X4bBm4rSlt",
	"4SSd442R31DpdYeNjBuLKao3QmeGxoAyCFPwcQSFx8em7JyR4iytT7JVQpdrzzqbnM3UVdUk/zhpRjAD",
	"NyzU45aztAqR3ys5T4qtAKFfjz/i+0ZFRvKR3qPzz6r1lNym7x7o6zXeweB9v5HOV1BYSlg+04mBvTEW",
	"GZaQ+s36t+mbNUn8bZFNbG26PpeYYqJNeDwXFuUaodPrF+J1t1293S+iSPipc2pNIkYxI93WJj5cPnUv",
	"WEzw/9W9hRhqR5uK3H6HfaZj5tMSoYjf+hHH1kwqVSB7IyoPQt4xItG87Wjqi5jF3SVx3NUWNXMdolg2",
	"2elFDPlxRrrtPTHj3lbQVJAGPQbPM57uIJe7Xi2fVtDmfXwsihlt5qJ7UXhhOc0fNXEqc6PgudLOesyD",
	"U0aht2YLBYziJ+cPXzwfQ8/SSL+uJxrBG1GxAJ6u4+C99R2eEq7IUGATbzVbYWwwttzoNtlx4umVG7EK",
	"38CIcZW6crHO2NoKhNm1yZ7HkYm+V2zFLdVcxDSZiLr5JbCAAmu6jczn/wUAAP//sMDJmDITAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
