// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
	"time"
)

type MagicLink struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
	UsedAt    sql.NullTime `json:"used_at"`
}

type Session struct {
	ID        string    `json:"id"`
	UserID    int64     `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

type SubRequest struct {
	ID             int64          `json:"id"`
	ShowID         int64          `json:"show_id"`
	PostedByUserID int64          `json:"posted_by_user_id"`
	TakenByUserID  sql.NullInt64  `json:"taken_by_user_id"`
	StartTime      time.Time      `json:"start_time"`
	EndTime        time.Time      `json:"end_time"`
	Notes          sql.NullString `json:"notes"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID        int64          `json:"id"`
	Email     string         `json:"email"`
	Role      sql.NullString `json:"role"`
	IsEnabled bool           `json:"is_enabled"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
