// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (email, role) VALUES (?, ?)
`

type CreateUserParams struct {
	Email string         `json:"email"`
	Role  sql.NullString `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser, arg.Email, arg.Role)
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, role, is_enabled, created_at FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.IsEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, role, is_enabled, created_at FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.IsEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const importUser = `-- name: ImportUser :exec
INSERT INTO users (email, role) VALUES (?, 'member') ON CONFLICT (email) DO NOTHING
`

func (q *Queries) ImportUser(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, importUser, email)
	return err
}

const listActiveUsers = `-- name: ListActiveUsers :many
SELECT id, email, role, is_enabled, created_at FROM users WHERE is_enabled = true ORDER BY email ASC
`

func (q *Queries) ListActiveUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listActiveUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.IsEnabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, role, is_enabled, created_at FROM users ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.IsEnabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserEnabled = `-- name: UpdateUserEnabled :execresult
UPDATE users SET is_enabled = ? WHERE id = ?
`

type UpdateUserEnabledParams struct {
	IsEnabled bool  `json:"is_enabled"`
	ID        int64 `json:"id"`
}

func (q *Queries) UpdateUserEnabled(ctx context.Context, arg UpdateUserEnabledParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserEnabled, arg.IsEnabled, arg.ID)
}

const updateUserRole = `-- name: UpdateUserRole :execresult
UPDATE users SET role = ? WHERE id = ?
`

type UpdateUserRoleParams struct {
	Role sql.NullString `json:"role"`
	ID   int64          `json:"id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserRole, arg.Role, arg.ID)
}

const updateUserRoleAndEnabled = `-- name: UpdateUserRoleAndEnabled :execresult
UPDATE users SET role = ?, is_enabled = ? WHERE id = ?
`

type UpdateUserRoleAndEnabledParams struct {
	Role      sql.NullString `json:"role"`
	IsEnabled bool           `json:"is_enabled"`
	ID        int64          `json:"id"`
}

func (q *Queries) UpdateUserRoleAndEnabled(ctx context.Context, arg UpdateUserRoleAndEnabledParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserRoleAndEnabled, arg.Role, arg.IsEnabled, arg.ID)
}
