// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for PatchSubRequestsIdJSONBodyAction.
const (
	Take   PatchSubRequestsIdJSONBodyAction = "take"
	Untake PatchSubRequestsIdJSONBodyAction = "untake"
)

// Valid indicates whether the value is a known member of the PatchSubRequestsIdJSONBodyAction enum.
func (e PatchSubRequestsIdJSONBodyAction) Valid() bool {
	switch e {
	case Take:
		return true
	case Untake:
		return true
	default:
		return false
	}
}

// Defines values for PostUsersFormdataBodyRole.
const (
	PostUsersFormdataBodyRoleAdmin  PostUsersFormdataBodyRole = "admin"
	PostUsersFormdataBodyRoleMember PostUsersFormdataBodyRole = "member"
)

// Valid indicates whether the value is a known member of the PostUsersFormdataBodyRole enum.
func (e PostUsersFormdataBodyRole) Valid() bool {
	switch e {
	case PostUsersFormdataBodyRoleAdmin:
		return true
	case PostUsersFormdataBodyRoleMember:
		return true
	default:
		return false
	}
}

// Defines values for PostUsersIdJSONBodyRole.
const (
	PostUsersIdJSONBodyRoleAdmin  PostUsersIdJSONBodyRole = "admin"
	PostUsersIdJSONBodyRoleMember PostUsersIdJSONBodyRole = "member"
)

// Valid indicates whether the value is a known member of the PostUsersIdJSONBodyRole enum.
func (e PostUsersIdJSONBodyRole) Valid() bool {
	switch e {
	case PostUsersIdJSONBodyRoleAdmin:
		return true
	case PostUsersIdJSONBodyRoleMember:
		return true
	default:
		return false
	}
}

// Defines values for PostUsersIdFormdataBodyIsEnabled.
const (
	False PostUsersIdFormdataBodyIsEnabled = "false"
	True  PostUsersIdFormdataBodyIsEnabled = "true"
)

// Valid indicates whether the value is a known member of the PostUsersIdFormdataBodyIsEnabled enum.
func (e PostUsersIdFormdataBodyIsEnabled) Valid() bool {
	switch e {
	case False:
		return true
	case True:
		return true
	default:
		return false
	}
}

// Defines values for PostUsersIdFormdataBodyRole.
const (
	Admin  PostUsersIdFormdataBodyRole = "admin"
	Member PostUsersIdFormdataBodyRole = "member"
)

// Valid indicates whether the value is a known member of the PostUsersIdFormdataBodyRole enum.
func (e PostUsersIdFormdataBodyRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Member:
		return true
	default:
		return false
	}
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email openapi_types.Email `json:"email"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message *string `json:"message,omitempty"`
}

// GetAuthVerifyParams defines parameters for GetAuthVerify.
type GetAuthVerifyParams struct {
	Token string `form:"token" json:"token"`
}

// PostSubRequestsFormdataBody defines parameters for PostSubRequests.
type PostSubRequestsFormdataBody struct {
	EndTime   string  `form:"end_time" json:"end_time"`
	Notes     *string `form:"notes,omitempty" json:"notes,omitempty"`
	Show      int     `form:"show" json:"show"`
	StartTime string  `form:"start_time" json:"start_time"`
}

// PatchSubRequestsIdJSONBody defines parameters for PatchSubRequestsId.
type PatchSubRequestsIdJSONBody struct {
	Action PatchSubRequestsIdJSONBodyAction `json:"action"`
}

// PatchSubRequestsIdJSONBodyAction defines parameters for PatchSubRequestsId.
type PatchSubRequestsIdJSONBodyAction string

// PostUsersFormdataBody defines parameters for PostUsers.
type PostUsersFormdataBody struct {
	Email openapi_types.Email        `form:"email" json:"email"`
	Role  *PostUsersFormdataBodyRole `form:"role,omitempty" json:"role,omitempty"`
}

// PostUsersFormdataBodyRole defines parameters for PostUsers.
type PostUsersFormdataBodyRole string

// PostUsersIdJSONBody defines parameters for PostUsersId.
type PostUsersIdJSONBody struct {
	IsEnabled *bool                    `json:"is_enabled,omitempty"`
	Role      *PostUsersIdJSONBodyRole `json:"role,omitempty"`
}

// PostUsersIdFormdataBody defines parameters for PostUsersId.
type PostUsersIdFormdataBody struct {
	IsEnabled *PostUsersIdFormdataBodyIsEnabled `form:"is_enabled,omitempty" json:"is_enabled,omitempty"`
	Role      *PostUsersIdFormdataBodyRole      `form:"role,omitempty" json:"role,omitempty"`
}

// PostUsersIdJSONBodyRole defines parameters for PostUsersId.
type PostUsersIdJSONBodyRole string

// PostUsersIdFormdataBodyIsEnabled defines parameters for PostUsersId.
type PostUsersIdFormdataBodyIsEnabled string

// PostUsersIdFormdataBodyRole defines parameters for PostUsersId.
type PostUsersIdFormdataBodyRole string

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// PostAuthLoginFormdataRequestBody defines body for PostAuthLogin for application/x-www-form-urlencoded ContentType.
type PostAuthLoginFormdataRequestBody = LoginRequest

// PostSubRequestsFormdataRequestBody defines body for PostSubRequests for application/x-www-form-urlencoded ContentType.
type PostSubRequestsFormdataRequestBody PostSubRequestsFormdataBody

// PatchSubRequestsIdJSONRequestBody defines body for PatchSubRequestsId for application/json ContentType.
type PatchSubRequestsIdJSONRequestBody PatchSubRequestsIdJSONBody

// PostUsersFormdataRequestBody defines body for PostUsers for application/x-www-form-urlencoded ContentType.
type PostUsersFormdataRequestBody PostUsersFormdataBody

// PostUsersIdJSONRequestBody defines body for PostUsersId for application/json ContentType.
type PostUsersIdJSONRequestBody PostUsersIdJSONBody

// PostUsersIdFormdataRequestBody defines body for PostUsersId for application/x-www-form-urlencoded ContentType.
type PostUsersIdFormdataRequestBody PostUsersIdFormdataBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Home page or login page
	// (GET /)
	Get(w http.ResponseWriter, r *http.Request)
	// Admin dashboard
	// (GET /admin)
	GetAdmin(w http.ResponseWriter, r *http.Request)
	// Authenticated application page
	// (GET /app)
	GetApp(w http.ResponseWriter, r *http.Request)
	// Request a magic link for login
	// (POST /auth/login)
	PostAuthLogin(w http.ResponseWriter, r *http.Request)
	// Logout and invalidate sessions
	// (POST /auth/logout)
	PostAuthLogout(w http.ResponseWriter, r *http.Request)
	// Verify magic link and create session
	// (GET /auth/verify)
	GetAuthVerify(w http.ResponseWriter, r *http.Request, params GetAuthVerifyParams)
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Create a new sub request
	// (POST /sub-requests)
	PostSubRequests(w http.ResponseWriter, r *http.Request)
	// Delete a sub request
	// (DELETE /sub-requests/{id})
	DeleteSubRequestsId(w http.ResponseWriter, r *http.Request, id int)
	// Sub request details page
	// (GET /sub-requests/{id})
	GetSubRequestsId(w http.ResponseWriter, r *http.Request, id int)
	// Take or untake a sub request
	// (PATCH /sub-requests/{id})
	PatchSubRequestsId(w http.ResponseWriter, r *http.Request, id int)
	// Create a new user
	// (POST /users)
	PostUsers(w http.ResponseWriter, r *http.Request)
	// Import users from Spinitron
	// (POST /users/import/spinitron)
	PostUsersImportSpinitron(w http.ResponseWriter, r *http.Request)
	// Update a user's status
	// (POST /users/{id})
	PostUsersId(w http.ResponseWriter, r *http.Request, id int)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Home page or login page
// (GET /)
func (_ Unimplemented) Get(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Admin dashboard
// (GET /admin)
func (_ Unimplemented) GetAdmin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Authenticated application page
// (GET /app)
func (_ Unimplemented) GetApp(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Request a magic link for login
// (POST /auth/login)
func (_ Unimplemented) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout and invalidate sessions
// (POST /auth/logout)
func (_ Unimplemented) PostAuthLogout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Verify magic link and create session
// (GET /auth/verify)
func (_ Unimplemented) GetAuthVerify(w http.ResponseWriter, r *http.Request, params GetAuthVerifyParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new sub request
// (POST /sub-requests)
func (_ Unimplemented) PostSubRequests(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a sub request
// (DELETE /sub-requests/{id})
func (_ Unimplemented) DeleteSubRequestsId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Sub request details page
// (GET /sub-requests/{id})
func (_ Unimplemented) GetSubRequestsId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Take or untake a sub request
// (PATCH /sub-requests/{id})
func (_ Unimplemented) PatchSubRequestsId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new user
// (POST /users)
func (_ Unimplemented) PostUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Import users from Spinitron
// (POST /users/import/spinitron)
func (_ Unimplemented) PostUsersImportSpinitron(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a user's status
// (POST /users/{id})
func (_ Unimplemented) PostUsersId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Get operation middleware
func (siw *ServerInterfaceWrapper) Get(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Get(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdmin operation middleware
func (siw *ServerInterfaceWrapper) GetAdmin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdmin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApp operation middleware
func (siw *ServerInterfaceWrapper) GetApp(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthVerify operation middleware
func (siw *ServerInterfaceWrapper) GetAuthVerify(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAuthVerifyParams

	// ------------- Required query parameter "token" -------------

	if paramValue := r.URL.Query().Get("token"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "token"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "token", r.URL.Query(), &params.Token, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthVerify(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostSubRequests operation middleware
func (siw *ServerInterfaceWrapper) PostSubRequests(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostSubRequests(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSubRequestsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteSubRequestsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSubRequestsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSubRequestsId operation middleware
func (siw *ServerInterfaceWrapper) GetSubRequestsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSubRequestsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchSubRequestsId operation middleware
func (siw *ServerInterfaceWrapper) PatchSubRequestsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchSubRequestsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUsers operation middleware
func (siw *ServerInterfaceWrapper) PostUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUsersImportSpinitron operation middleware
func (siw *ServerInterfaceWrapper) PostUsersImportSpinitron(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsersImportSpinitron(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUsersId operation middleware
func (siw *ServerInterfaceWrapper) PostUsersId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsersId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/", wrapper.Get)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin", wrapper.GetAdmin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/app", wrapper.GetApp)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.PostAuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.PostAuthLogout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/verify", wrapper.GetAuthVerify)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/sub-requests", wrapper.PostSubRequests)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/sub-requests/{id}", wrapper.DeleteSubRequestsId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/sub-requests/{id}", wrapper.GetSubRequestsId)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/sub-requests/{id}", wrapper.PatchSubRequestsId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users", wrapper.PostUsers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/import/spinitron", wrapper.PostUsersImportSpinitron)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/{id}", wrapper.PostUsersId)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xX31MbNxD+VzRqZ0pmDuyE9KF+o3TSuAmBgdCXDJOR79Y+xSfpWO3xo4z/985KNr4f",
	"xjguJbzA+bQn7fft7rerO5k6UzoLlrwc3Emf5mBUePzoJtqewmUFnvh3ia4EJA1hFYzSBT+MHRpFcjB/",
	"k0i6LUEOpCfUdiJns0QiXFYaIZODL3Ori3szN/oGKclZIo/AezWBU/Clsx66R5powI/dM1rb8Sttx46N",
	"M/Ap6pK0s3IgD06GYuxQHGgUh+4KUHjwXjsrjLJqAgYsCWUz4XN3LQhVOtV2ssfANBV8xvLLg5OhTOQV",
	"oI97v97r7/UZiyvBqlLLgdzf6+/ty0SWivKAosd/JhAoZXSK/RpmciD/BJJMVsQfjN/0+/wvdZbAhk8I",
	"bqiXkymW0VpFyCxpwX7/+eijWOzDy74yRuEtLzkDolQTEA5FwVEPv4JVT2VG23UuHwSDZ/I7kW/7r7sx",
	"Pbeqotyh/geyaLTfNXrncKSzDGwLfgAgMuXzkVOYzWGX5VrQZfmiIDcBVZSDJZ0qgkyosiz4kTO8FtaK",
	"8l6Idagz51fgPHGeeK8gBDKWMXj63WW3LaS1M3rfvLNNwD8jjOVA/tRbSk1vrjO9hsiwZ/Wtbnavr693",
	"WWB2KyzApi5jEdly74YQEVYwezSC2+Nqi9mKMB+piU5Foe1U+PtI97uRHtorVehMYI2lZbDn+IQSZrnf",
	"eFHIzWC7ijaKNtu1uNnvv+l6dgqZRkhJkBO5M7BNssbjguDqCFQRLCTZ1/y/AtTj27VFWVH+d7RivUVl",
	"gAC9HHy5k5zn8rIC5DWrDFcguSks8nqZFcmaUr3YhhVWVZaTh8hZxNehgJuSHRHRsyZREVk9ysxZilDj",
	"K9KVgyooX8fU+2ixmYKVhdKtzIcbZcrQC48/rOj4nVQ//tBuOcEBkeaQTqPTvhrtzjPcr0/Ss2p0ujDc",
	"VJQ2UJLWeGOzr6TNqmEjkdZRtOqs8MxQW9CWYAIYVkghPbRla0YKuzQ+SZYOXaycddYpm62Kok7+YcwZ",
	"JSxcC1+NGsrSCETvTmezmLEFEHTj8Ud4X4vIMHug9nj+WZaezjapu3v6OoX3pv+2W0hnSygiOpw90cQg",
	"dqwjQTnEenP4Kn6zwolPjsTYVbatc5EpoZqEJw+W6I/g9AfPbN/BZjPUpHTh58NNmLTTfIV08OtnYnW7",
	"OampQCqNHLAWVYZlgdSUlaCy4eHisZvWfIPv14sNyqsquU1nm88sTzS4P54mbPFb1+LQ2XGhUxI7qkBQ",
	"2a1gEu2rVl59VtPQryPH7Wpleax8SJZ1Deo8mPx/rWnTm3ci0RVQzyADZgQoExlvdRfbXtYfz6D1k9FI",
	"pVMej1T76vXM6TR7sC1ymGsB72lTOqSeL7XVhM5ukAHD8MnZ/RdPx9CTFNKvq4kmQKsK4QGvAAUgOmzx",
	"FHEFhrwYozNiibHG2GJ0eIylFy7D2n8Fq0ZFrMn5OSPnClB22xJrV1Py3wSh6eJ9t8CKu8VYFX5Vs3ga",
	"z7frJBz4RQsRO3+dHX8K89RWFSF23jk0r15gJ2oUzXlAK1Qom1+88KSo4uvtbPZvAAAA//+4vq8MgxUA",
	"AA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
